version: '3'

networks:
  app-network:
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    depends_on:
      - frontend
      - fastapi

  fastapi:
    build: 
      context: ./FastAPI
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./FastAPI:/app
    environment:
      - PYTHONPATH=/app
    networks:
      - app-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    depends_on:
      - fastapi 